export const INITIAL_PRODUCTS = [
  // --- GIFTS & TOYS (8 Products) ---
  {
    id: "prod-1",
    name: "Teddy Bear Soft Toy",
    slug: "teddy-bear-soft-toy",
    price: 399,
    discountPrice: 299,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Soft Toys",
    image: "/assets/products/teddy-bear.png",
    rating: 4.8,
    reviewCount: 42,
    stock: 25,
    featured: true,
    active: true,
    description: "Ultra-soft premium plush teddy bear with a classic satin bow. Made with child-safe, washable fabric."
  },
  {
    id: "prod-2",
    name: "Metal Bike Model",
    slug: "metal-bike-model",
    price: 649,
    discountPrice: 499,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Metal Toys",
    image: "/assets/products/metal-bike.png",
    rating: 4.7,
    reviewCount: 28,
    stock: 14,
    featured: true,
    active: true,
    description: "Detailed vintage metal motorcycle collectible model with realistic kickstand and fine metallic finish."
  },
  {
    id: "prod-3",
    name: "Ceramic Owl Showpiece",
    slug: "ceramic-owl-showpiece",
    price: 450,
    discountPrice: 349,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Ceramic Toys",
    image: "/assets/products/ceramic-owl.png",
    rating: 4.9,
    reviewCount: 35,
    stock: 18,
    featured: true,
    active: true,
    description: "Artisan hand-painted ceramic owl figurine symbolizing wisdom and prosperity."
  },
  {
    id: "prod-4",
    name: "Plastic Car Toy",
    slug: "plastic-car-toy",
    price: 249,
    discountPrice: 199,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Plastic Toys",
    image: "/assets/products/plastic-car.png",
    rating: 4.5,
    reviewCount: 52,
    stock: 40,
    featured: true,
    active: true,
    description: "High-speed friction powered sports racing car with aerodynamic styling."
  },
  {
    id: "prod-5",
    name: "Wooden Train Toy",
    slug: "wooden-train-toy",
    price: 499,
    discountPrice: 399,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Wooden Toys",
    image: "/assets/products/wooden-train.png",
    rating: 4.8,
    reviewCount: 19,
    stock: 12,
    featured: true,
    active: true,
    description: "Eco-friendly handcrafted wooden locomotive engine toy painted with non-toxic natural colors."
  },
  {
    id: "prod-23",
    name: "Velvet Soft Dancing Doll",
    slug: "velvet-soft-dancing-doll",
    price: 499,
    discountPrice: 389,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Soft Toys",
    image: "/assets/products/teddy-bear.png",
    rating: 4.7,
    reviewCount: 22,
    stock: 16,
    featured: false,
    active: true,
    description: "Delightful plush ragdoll with braided yarn hair, ruffled frock, and embroidered smiling face."
  },
  {
    id: "prod-25",
    name: "Lord Krishna Flute Idol Figurine",
    slug: "krishna-flute-idol-figurine",
    price: 699,
    discountPrice: 549,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Ceramic Toys",
    image: "/assets/products/ceramic-owl.png",
    rating: 5.0,
    reviewCount: 45,
    stock: 20,
    featured: true,
    active: true,
    description: "Exquisite hand-painted Lord Krishna playing flute decorative showpiece with golden ornaments."
  },
  {
    id: "prod-26",
    name: "Remote Control Stunt Rover",
    slug: "remote-control-stunt-rover",
    price: 899,
    discountPrice: 699,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Plastic Toys",
    image: "/assets/products/plastic-car.png",
    rating: 4.6,
    reviewCount: 38,
    stock: 15,
    featured: false,
    active: true,
    description: "360-degree rotating RC stunt car with bright LED lights and rechargeable battery pack."
  },

  // --- SLIPPERS (8 Products) ---
  {
    id: "prod-6",
    name: "Men's Slipper",
    slug: "mens-slipper-black-red",
    price: 399,
    discountPrice: 299,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Men",
    image: "/assets/products/men-slipper.png",
    rating: 4.6,
    reviewCount: 64,
    stock: 30,
    sizes: ["7", "8", "9", "10"],
    featured: true,
    active: true,
    description: "Comfortable ergonomic men's slip-on slide with textured footbed and anti-skid sole."
  },
  {
    id: "prod-7",
    name: "Women's Slipper",
    slug: "womens-slipper-peach",
    price: 449,
    discountPrice: 349,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Women",
    image: "/assets/products/women-slipper.png",
    rating: 4.7,
    reviewCount: 48,
    stock: 22,
    sizes: ["5", "6", "7", "8"],
    featured: true,
    active: true,
    description: "Soft cushioned pastel peach everyday slides for women with arch support."
  },
  {
    id: "prod-8",
    name: "Kids' Slipper",
    slug: "kids-slipper-blue-clog",
    price: 299,
    discountPrice: 249,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Kids",
    image: "/assets/products/kids-slipper.png",
    rating: 4.9,
    reviewCount: 39,
    stock: 15,
    sizes: ["Kids 1", "Kids 2", "Kids 3"],
    featured: true,
    active: true,
    description: "Playful cartoon character clog slippers for kids with convertible heel strap."
  },
  {
    id: "prod-24",
    name: "Men's Orthopedic Comfort Slipper",
    slug: "mens-orthopedic-comfort-slipper",
    price: 499,
    discountPrice: 379,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Men",
    image: "/assets/products/men-slipper.png",
    rating: 4.8,
    reviewCount: 38,
    stock: 22,
    sizes: ["8", "9", "10"],
    featured: false,
    active: true,
    description: "Doctor-recommended orthopedic slippers for heel pain and diabetic foot relief."
  },
  {
    id: "prod-27",
    name: "Women's Floral Daily Slippers",
    slug: "womens-floral-daily-slippers",
    price: 349,
    discountPrice: 279,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Women",
    image: "/assets/products/women-slipper.png",
    rating: 4.7,
    reviewCount: 31,
    stock: 25,
    sizes: ["6", "7", "8"],
    featured: false,
    active: true,
    description: "Comfortable floral pattern home slippers with anti-sweat lining."
  },
  {
    id: "prod-28",
    name: "Kids' Light-Up Dino Slippers",
    slug: "kids-light-up-dino-slippers",
    price: 399,
    discountPrice: 299,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Kids",
    image: "/assets/products/kids-slipper.png",
    rating: 4.9,
    reviewCount: 50,
    stock: 18,
    sizes: ["Kids 2", "Kids 3", "Kids 4"],
    featured: false,
    active: true,
    description: "Dinosaur themed light-up clog slippers that illuminate with every step."
  },
  {
    id: "prod-29",
    name: "Men's Classic Thong Flip Flops",
    slug: "mens-classic-thong-flip-flops",
    price: 249,
    discountPrice: 189,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Men",
    image: "/assets/products/men-slipper.png",
    rating: 4.5,
    reviewCount: 42,
    stock: 35,
    sizes: ["7", "8", "9", "10"],
    featured: false,
    active: true,
    description: "Durable waterproof rubber flip flops with soft strap for bath and casual wear."
  },
  {
    id: "prod-30",
    name: "Women's Wedge Heel Slides",
    slug: "womens-wedge-heel-slides",
    price: 549,
    discountPrice: 429,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Women",
    image: "/assets/products/women-slipper.png",
    rating: 4.8,
    reviewCount: 26,
    stock: 14,
    sizes: ["6", "7", "8"],
    featured: false,
    active: true,
    description: "Lightweight polyurethane platform wedge slippers for house and patio."
  },

  // --- FANCY ITEMS & JEWELRY (8 Products) ---
  {
    id: "prod-9",
    name: "Fancy Earrings",
    slug: "fancy-earrings-traditional",
    price: 220,
    discountPrice: 159,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Earrings",
    image: "/assets/products/fancy-earrings.png",
    rating: 4.8,
    reviewCount: 71,
    stock: 45,
    featured: true,
    active: true,
    description: "Antique gold-finish jhumka earrings adorned with ruby-red stones and pearl drop beads."
  },
  {
    id: "prod-10",
    name: "Gold Chain",
    slug: "gold-chain-pendant",
    price: 499,
    discountPrice: 349,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Chains",
    image: "/assets/products/gold-chain.png",
    rating: 4.6,
    reviewCount: 33,
    stock: 20,
    featured: true,
    active: true,
    description: "Dainty micro-plated golden cable chain featuring an elegant geometric charm pendant."
  },
  {
    id: "prod-11",
    name: "Makeup Kit",
    slug: "makeup-kit-palette",
    price: 699,
    discountPrice: 499,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Makeup",
    image: "/assets/products/makeup-kit.png",
    rating: 4.7,
    reviewCount: 56,
    stock: 16,
    featured: true,
    active: true,
    description: "All-in-one beauty palette featuring 12 vibrant eyeshadow shades, blush powders, and lipsticks."
  },
  {
    id: "prod-12",
    name: "Perfume",
    slug: "royal-blue-perfume",
    price: 799,
    discountPrice: 599,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Perfumes",
    image: "/assets/products/perfume.png",
    rating: 4.9,
    reviewCount: 88,
    stock: 25,
    featured: true,
    active: true,
    description: "Long-lasting Eau de Parfum with top notes of bergamot and cedarwood in deep cobalt bottle."
  },
  {
    id: "prod-22",
    name: "Sparkling Crystal Finger Ring",
    slug: "sparkling-crystal-finger-ring",
    price: 180,
    discountPrice: 129,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Rings",
    image: "/assets/products/gold-chain.png",
    rating: 4.6,
    reviewCount: 29,
    stock: 30,
    featured: false,
    active: true,
    description: "Adjustable golden brass ring embedded with high-grade cubic zirconia crystal."
  },
  {
    id: "prod-31",
    name: "Traditional Temple Bangles Set of 4",
    slug: "traditional-temple-bangles-set",
    price: 349,
    discountPrice: 249,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Bangles",
    image: "/assets/products/fancy-earrings.png",
    rating: 4.8,
    reviewCount: 44,
    stock: 22,
    featured: false,
    active: true,
    description: "Traditional south Indian temple jewelry bangles with goddess motifs."
  },
  {
    id: "prod-32",
    name: "Kawaii 3D Cartoon Stickers Pack of 50",
    slug: "kawaii-3d-cartoon-stickers-pack",
    price: 99,
    discountPrice: 59,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Stickers",
    image: "/assets/products/color-pencils.png",
    rating: 4.9,
    reviewCount: 65,
    stock: 75,
    featured: false,
    active: true,
    description: "Waterproof vinyl cartoon stickers for scrapbooks, phone cases, and water bottles."
  },
  {
    id: "prod-33",
    name: "Matte Velvet Lip Color Duo",
    slug: "matte-velvet-lip-color-duo",
    price: 299,
    discountPrice: 199,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Makeup",
    image: "/assets/products/makeup-kit.png",
    rating: 4.7,
    reviewCount: 37,
    stock: 30,
    featured: false,
    active: true,
    description: "Transfer-proof smudge-resistant liquid lipstick with nourishing Vitamin E."
  },

  // --- STATIONERY & ART SUPPLIES (8 Products) ---
  {
    id: "prod-13",
    name: "Spiral Notebook with Pen",
    slug: "spiral-notebook-with-pen",
    price: 120,
    discountPrice: 89,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Notebooks",
    image: "/assets/products/spiral-notebook.png",
    rating: 4.6,
    reviewCount: 92,
    stock: 50,
    featured: true,
    active: true,
    description: "Hardcover blue executive wirebound notebook with smooth 80 GSM bleed-proof ruled pages."
  },
  {
    id: "prod-14",
    name: "Ballpoint Pens Pack",
    slug: "ballpoint-pens-pack",
    price: 60,
    discountPrice: 49,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Pens",
    image: "/assets/products/ballpoint-pens.png",
    rating: 4.8,
    reviewCount: 110,
    stock: 100,
    featured: true,
    active: true,
    description: "Set of smooth gliding 0.7mm tip blue and red ballpoint pens with waterproof ink."
  },
  {
    id: "prod-15",
    name: "Drawing Pencils Set",
    slug: "drawing-pencils-set",
    price: 100,
    discountPrice: 79,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Pencils",
    image: "/assets/products/drawing-pencils.png",
    rating: 4.7,
    reviewCount: 44,
    stock: 60,
    featured: true,
    active: true,
    description: "Assorted graphite artist sketch pencils graded from 2B to 8B for sketching."
  },
  {
    id: "prod-16",
    name: "Eraser & Sharpener Combo",
    slug: "eraser-sharpener-combo",
    price: 40,
    discountPrice: 29,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Erasers",
    image: "/assets/products/eraser-combo.png",
    rating: 4.5,
    reviewCount: 75,
    stock: 80,
    featured: true,
    active: true,
    description: "Dust-free soft pencil erasers paired with precision steel blade sharpeners."
  },
  {
    id: "prod-17",
    name: "Color Pencils Pack",
    slug: "color-pencils-12-shades",
    price: 150,
    discountPrice: 119,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Color Pencils",
    image: "/assets/products/color-pencils.png",
    rating: 4.8,
    reviewCount: 63,
    stock: 40,
    featured: true,
    active: true,
    description: "Set of 12 vibrant pre-sharpened color pencils with break-resistant leads."
  },
  {
    id: "prod-18",
    name: "Camel Drawing Book",
    slug: "camel-drawing-book-20-pages",
    price: 80,
    discountPrice: 65,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Drawing Books",
    image: "/assets/products/camel-drawing-book.png",
    rating: 4.9,
    reviewCount: 82,
    stock: 65,
    featured: true,
    active: true,
    description: "Premium Camlin artist drawing book featuring heavy cartridge paper for colors and sketch pens."
  },
  {
    id: "prod-19",
    name: "Camlin Geometry Box",
    slug: "camlin-geometry-box",
    price: 190,
    discountPrice: 160,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Geometry Boxes",
    image: "/assets/products/spiral-notebook.png",
    rating: 4.8,
    reviewCount: 54,
    stock: 35,
    featured: false,
    active: true,
    description: "Full mathematical instrument box with self-centering compass, divider, protractor, and scales."
  },
  {
    id: "prod-20",
    name: "Classmate Long Notebook 192 Pgs",
    slug: "classmate-long-notebook-192-pgs",
    price: 85,
    discountPrice: 75,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Record Books",
    image: "/assets/products/camel-drawing-book.png",
    rating: 4.9,
    reviewCount: 120,
    stock: 120,
    featured: false,
    active: true,
    description: "Single line long notebook with elemental chlorine-free paper and sturdy binding."
  },
  {
    id: "prod-34",
    name: "Rose Blossom Natural Pocket Perfume 50ml",
    slug: "rose-blossom-pocket-perfume",
    price: 249,
    discountPrice: 179,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Perfumes",
    image: "/assets/products/earrings.png",
    rating: 4.7,
    reviewCount: 29,
    stock: 22,
    featured: false,
    active: true,
    description: "Long-lasting non-alcoholic floral fragrance spray inspired by fresh Ooty rose gardens."
  },
  {
    id: "prod-35",
    name: "Holographic 3D Stickers Mega Pack",
    slug: "holographic-3d-stickers-mega-pack",
    price: 99,
    discountPrice: 69,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Stickers",
    image: "/assets/products/bangles.png",
    rating: 4.8,
    reviewCount: 65,
    stock: 50,
    featured: false,
    active: true,
    description: "Waterproof vinyl stickers featuring cute animals and motivational quotes."
  },
  {
    id: "prod-36",
    name: "Herbal Compact Makeup Powder Kit",
    slug: "herbal-compact-makeup-powder-kit",
    price: 299,
    discountPrice: 229,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Makeup",
    image: "/assets/products/earrings.png",
    rating: 4.5,
    reviewCount: 21,
    stock: 16,
    featured: false,
    active: true,
    description: "All-day oil control face powder with SPF 15 protection, infused with sandalwood."
  },
  {
    id: "prod-37",
    name: "Cello Butterflow Blue Ballpoint Pens (Pack of 5)",
    slug: "cello-butterflow-blue-pens-pack",
    price: 99,
    discountPrice: 79,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Pens",
    image: "/assets/products/pen-set.png",
    rating: 4.9,
    reviewCount: 94,
    stock: 60,
    featured: true,
    active: true,
    description: "India's favorite ball pen with lubriflow ink system and ergonomic rubber grip."
  },
  {
    id: "prod-38",
    name: "Reynolds 045 Black Fine Ballpoint Pens (Pack of 5)",
    slug: "reynolds-045-black-pens-pack",
    price: 99,
    discountPrice: 79,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Pens",
    image: "/assets/products/pen-set.png",
    rating: 4.7,
    reviewCount: 48,
    stock: 45,
    featured: false,
    active: true,
    description: "Classic laser tip 0.7mm fine point pens engineered for crisp examination writing."
  },
  {
    id: "prod-39",
    name: "Apsara Platinum Extra Dark Pencils (Pack of 10)",
    slug: "apsara-platinum-extra-dark-pencils",
    price: 70,
    discountPrice: 59,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Pencils",
    image: "/assets/products/color-pencils.png",
    rating: 4.9,
    reviewCount: 82,
    stock: 55,
    featured: false,
    active: true,
    description: "Premium dark graphite lead pencils that require less pressure while writing."
  },
  {
    id: "prod-40",
    name: "Hardbound School Record Notebook 160 Pgs",
    slug: "hardbound-school-record-notebook-160pgs",
    price: 120,
    discountPrice: 99,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Record Books",
    image: "/assets/products/spiral-notebook.png",
    rating: 4.8,
    reviewCount: 37,
    stock: 40,
    featured: false,
    active: true,
    description: "Heavy hardboard binding with section-sewn pages for durability."
  },
  {
    id: "prod-41",
    name: "Camlin Artist Oil Pastels 25 Shades",
    slug: "camlin-artist-oil-pastels-25shades",
    price: 180,
    discountPrice: 149,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Art Supplies",
    image: "/assets/products/color-pencils.png",
    rating: 4.9,
    reviewCount: 44,
    stock: 26,
    featured: false,
    active: true,
    description: "Vibrant, inter-mixable oil pastels with smooth blending and rich opacity."
  },
  {
    id: "prod-42",
    name: "Stainless Steel Edge Transparent Scale 30cm",
    slug: "steel-edge-transparent-scale-30cm",
    price: 49,
    discountPrice: 35,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Scales",
    image: "/assets/products/geometry-box.png",
    rating: 4.6,
    reviewCount: 29,
    stock: 50,
    featured: false,
    active: true,
    description: "Clear acrylic ruler with a precision stainless steel cutting edge."
  },
  {
    id: "prod-43",
    name: "Non-Dust Jumbo Eraser & Sharpener Combo",
    slug: "non-dust-jumbo-eraser-sharpener-combo",
    price: 45,
    discountPrice: 35,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Erasers",
    image: "/assets/products/geometry-box.png",
    rating: 4.8,
    reviewCount: 60,
    stock: 75,
    featured: false,
    active: true,
    description: "Dust-free eraser that rolls up residue into strands without tearing paper."
  },
  {
    id: "prod-44",
    name: "Expanding Accordion Document File 12 Pockets",
    slug: "expanding-accordion-document-file-12pockets",
    price: 249,
    discountPrice: 199,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Files",
    image: "/assets/products/spiral-notebook.png",
    rating: 4.7,
    reviewCount: 33,
    stock: 22,
    featured: false,
    active: true,
    description: "Heavy-duty polypropylene accordion file with 12 tabbed compartments."
  }
];
