export const DEMO_PRODUCTS = [
  // --- ROW 1 (From Reference UI) ---
  {
    id: "prod-1",
    name: "Teddy Bear Soft Toy",
    slug: "teddy-bear-soft-toy",
    price: 399,
    discountPrice: 299,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Soft Toys",
    image: "/assets/products/teddy-bear.png",
    rating: 4.8,
    reviewCount: 42,
    stock: 25,
    featured: true,
    description: "Ultra-soft premium plush teddy bear with a classic satin bow. Made with child-safe, washable fabric. Perfect gift for birthdays and celebrations."
  },
  {
    id: "prod-2",
    name: "Metal Bike Model",
    slug: "metal-bike-model",
    price: 649,
    discountPrice: 499,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Metal Toys",
    image: "/assets/products/metal-bike.png",
    rating: 4.7,
    reviewCount: 28,
    stock: 14,
    featured: true,
    description: "Detailed vintage metal motorcycle collectible model with realistic kickstand, rubber tires, and fine metallic finish. Ideal for desk decor and gift."
  },
  {
    id: "prod-3",
    name: "Ceramic Owl Showpiece",
    slug: "ceramic-owl-showpiece",
    price: 450,
    discountPrice: 349,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Ceramic Toys",
    image: "/assets/products/ceramic-owl.png",
    rating: 4.9,
    reviewCount: 35,
    stock: 18,
    featured: true,
    description: "Artisan hand-painted ceramic owl figurine symbolizing wisdom and prosperity. High-gloss glaze finish suitable for living room or showcase."
  },
  {
    id: "prod-4",
    name: "Plastic Car Toy",
    slug: "plastic-car-toy",
    price: 249,
    discountPrice: 199,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Plastic Toys",
    image: "/assets/products/plastic-car.png",
    rating: 4.5,
    reviewCount: 52,
    stock: 40,
    featured: true,
    description: "High-speed friction powered sports racing car with aerodynamic styling, dynamic graphics, and durable non-toxic ABS plastic body."
  },
  {
    id: "prod-5",
    name: "Wooden Train Toy",
    slug: "wooden-train-toy",
    price: 499,
    discountPrice: 399,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Wooden Toys",
    image: "/assets/products/wooden-train.png",
    rating: 4.8,
    reviewCount: 19,
    stock: 12,
    featured: true,
    description: "Eco-friendly handcrafted wooden locomotive engine toy painted with non-toxic natural colors. Smooth rounded corners safe for toddlers."
  },
  {
    id: "prod-6",
    name: "Men's Slipper",
    slug: "mens-slipper-black-red",
    price: 399,
    discountPrice: 299,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Men",
    image: "/assets/products/men-slipper.png",
    rating: 4.6,
    reviewCount: 64,
    stock: 30,
    sizes: ["7", "8", "9", "10"],
    featured: true,
    description: "Comfortable ergonomic men's slip-on slide with textured footbed for acupressure support and anti-skid rubber outer sole."
  },

  // --- ROW 2 (From Reference UI) ---
  {
    id: "prod-7",
    name: "Women's Slipper",
    slug: "womens-slipper-peach",
    price: 449,
    discountPrice: 349,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Women",
    image: "/assets/products/women-slipper.png",
    rating: 4.7,
    reviewCount: 48,
    stock: 22,
    sizes: ["5", "6", "7", "8"],
    featured: true,
    description: "Soft cushioned pastel peach everyday slides for women. Water-resistant, featherlight EVA foam with arch support."
  },
  {
    id: "prod-8",
    name: "Kids' Slipper",
    slug: "kids-slipper-blue-clog",
    price: 299,
    discountPrice: 249,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Kids",
    image: "/assets/products/kids-slipper.png",
    rating: 4.9,
    reviewCount: 39,
    stock: 15,
    sizes: ["Kids 1", "Kids 2", "Kids 3"],
    featured: true,
    description: "Playful cartoon character clog slippers for kids with convertible heel strap for secure grip and ventilation ports."
  },
  {
    id: "prod-9",
    name: "Fancy Earrings",
    slug: "fancy-earrings-traditional",
    price: 220,
    discountPrice: 159,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Earrings",
    image: "/assets/products/fancy-earrings.png",
    rating: 4.8,
    reviewCount: 71,
    stock: 45,
    featured: true,
    description: "Intricately crafted antique gold-finish jhumka earrings adorned with ruby-red stones and dainty pearl drop beads."
  },
  {
    id: "prod-10",
    name: "Gold Chain",
    slug: "gold-chain-pendant",
    price: 499,
    discountPrice: 349,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Chains",
    image: "/assets/products/gold-chain.png",
    rating: 4.6,
    reviewCount: 33,
    stock: 20,
    featured: true,
    description: "Dainty micro-plated golden cable chain featuring an elegant geometric charm pendant. Tarnish-resistant coating for daily wear."
  },
  {
    id: "prod-11",
    name: "Makeup Kit",
    slug: "makeup-kit-palette",
    price: 699,
    discountPrice: 499,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Makeup",
    image: "/assets/products/makeup-kit.png",
    rating: 4.7,
    reviewCount: 56,
    stock: 16,
    featured: true,
    description: "All-in-one beauty palette featuring 12 vibrant eyeshadow shades, blush powders, compact mirror, and velvet matte lipsticks."
  },
  {
    id: "prod-12",
    name: "Perfume",
    slug: "royal-blue-perfume",
    price: 799,
    discountPrice: 599,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Perfumes",
    image: "/assets/products/perfume.png",
    rating: 4.9,
    reviewCount: 88,
    stock: 25,
    featured: true,
    description: "Long-lasting Eau de Parfum with top notes of bergamot, sea breeze, and rich cedarwood. 100ml spray bottle in deep cobalt glass."
  },

  // --- ROW 3 (From Reference UI) ---
  {
    id: "prod-13",
    name: "Spiral Notebook with Pen",
    slug: "spiral-notebook-with-pen",
    price: 120,
    discountPrice: 89,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Notebooks",
    image: "/assets/products/spiral-notebook.png",
    rating: 4.6,
    reviewCount: 92,
    stock: 50,
    featured: true,
    description: "Hardcover blue executive wirebound notebook with smooth 80 GSM bleed-proof ruled pages and matching ballpoint pen loop."
  },
  {
    id: "prod-14",
    name: "Ballpoint Pens Pack",
    slug: "ballpoint-pens-pack",
    price: 60,
    discountPrice: 49,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Pens",
    image: "/assets/products/ballpoint-pens.png",
    rating: 4.8,
    reviewCount: 110,
    stock: 100,
    featured: true,
    description: "Set of smooth gliding 0.7mm tip blue and red ballpoint pens with waterproof, smudge-resistant ink and textured grip."
  },
  {
    id: "prod-15",
    name: "Drawing Pencils Set",
    slug: "drawing-pencils-set",
    price: 100,
    discountPrice: 79,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Pencils",
    image: "/assets/products/drawing-pencils.png",
    rating: 4.7,
    reviewCount: 44,
    stock: 60,
    featured: true,
    description: "Assorted graphite artist sketch pencils graded from 2B to 8B for shading, technical drafting, and artistic sketching."
  },
  {
    id: "prod-16",
    name: "Eraser & Sharpener Combo",
    slug: "eraser-sharpener-combo",
    price: 40,
    discountPrice: 29,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Erasers",
    image: "/assets/products/eraser-combo.png",
    rating: 4.5,
    reviewCount: 75,
    stock: 80,
    featured: true,
    description: "Dust-free soft vinyl pencil erasers paired with precision rust-proof steel blade sharpeners with waste container."
  },
  {
    id: "prod-17",
    name: "Color Pencils Pack",
    slug: "color-pencils-12-shades",
    price: 150,
    discountPrice: 119,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Color Pencils",
    image: "/assets/products/color-pencils.png",
    rating: 4.8,
    reviewCount: 63,
    stock: 40,
    featured: true,
    description: "Set of 12 vibrant pre-sharpened color pencils with break-resistant leads for rich blending, shading, and school art projects."
  },
  {
    id: "prod-18",
    name: "Camel Drawing Book",
    slug: "camel-drawing-book-20-pages",
    price: 80,
    discountPrice: 65,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Drawing Books",
    image: "/assets/products/camel-drawing-book.png",
    rating: 4.9,
    reviewCount: 82,
    stock: 65,
    featured: true,
    description: "Premium Camlin artist drawing book featuring heavy cartridge paper ideal for watercolors, crayons, sketch pens, and poster paints."
  },

  // --- ADDITIONAL EXTENSIVE PRODUCTS TO EXCEED 24-30 REQUIREMENT ---
  {
    id: "prod-19",
    name: "Camlin Geometry Box",
    slug: "camlin-geometry-box",
    price: 190,
    discountPrice: 160,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Geometry Boxes",
    image: "/assets/products/spiral-notebook.png",
    rating: 4.8,
    reviewCount: 54,
    stock: 35,
    featured: false,
    description: "Full mathematical instrument box with self-centering compass, divider, protractor, set squares, and mechanical pencil."
  },
  {
    id: "prod-20",
    name: "Classmate Long Notebook 192 Pgs",
    slug: "classmate-long-notebook-192-pgs",
    price: 85,
    discountPrice: 75,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Record Books",
    image: "/assets/products/camel-drawing-book.png",
    rating: 4.9,
    reviewCount: 120,
    stock: 120,
    featured: false,
    description: "Single line long notebook with elemental chlorine-free paper, attractive cover designs, and sturdy binding for school and college."
  },
  {
    id: "prod-21",
    name: "Highlighter Marker Pens Set of 5",
    slug: "highlighter-marker-pens-set",
    price: 130,
    discountPrice: 99,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Markers",
    image: "/assets/products/color-pencils.png",
    rating: 4.7,
    reviewCount: 41,
    stock: 40,
    featured: false,
    description: "Fluorescent chisel tip text highlighters in neon yellow, green, pink, orange, and blue with anti-dry out ink."
  },
  {
    id: "prod-22",
    name: "Sparkling Crystal Finger Ring",
    slug: "sparkling-crystal-finger-ring",
    price: 180,
    discountPrice: 129,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Rings",
    image: "/assets/products/gold-chain.png",
    rating: 4.6,
    reviewCount: 29,
    stock: 30,
    featured: false,
    description: "Adjustable golden brass ring embedded with high-grade cubic zirconia crystal that sparkles from every angle."
  },
  {
    id: "prod-23",
    name: "Velvet Soft Dancing Doll",
    slug: "velvet-soft-dancing-doll",
    price: 499,
    discountPrice: 389,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Soft Toys",
    image: "/assets/products/teddy-bear.png",
    rating: 4.7,
    reviewCount: 22,
    stock: 16,
    featured: false,
    description: "Delightful plush ragdoll with braided yarn hair, ruffled frock, and embroidered smiling face. Huggable and safe."
  },
  {
    id: "prod-24",
    name: "Men's Orthopedic Comfort Slipper",
    slug: "mens-orthopedic-comfort-slipper",
    price: 499,
    discountPrice: 379,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Men",
    image: "/assets/products/men-slipper.png",
    rating: 4.8,
    reviewCount: 38,
    stock: 22,
    sizes: ["8", "9", "10"],
    featured: false,
    description: "Doctor-recommended orthopedic slippers for heel pain and diabetic foot relief with memory foam insole and broad strap."
  },
  {
    id: "prod-25",
    name: "Wooden Train Engine Handcrafted Toy",
    slug: "wooden-train-engine-toy",
    price: 349,
    discountPrice: 279,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Wooden Toys",
    image: "/assets/products/metal-bike.png",
    rating: 4.9,
    reviewCount: 19,
    stock: 15,
    featured: false,
    description: "Traditional Channapatna style non-toxic vegetable-dyed wooden locomotive toy with rolling wheels. Safe for toddlers."
  },
  {
    id: "prod-26",
    name: "Little Giant Panda Soft Plush Toy",
    slug: "little-giant-panda-soft-toy",
    price: 449,
    discountPrice: 329,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Soft Toys",
    image: "/assets/products/teddy-bear.png",
    rating: 4.8,
    reviewCount: 31,
    stock: 20,
    featured: false,
    description: "Adorable black and white baby panda plushie holding a green bamboo stalk. Super-soft down cotton filling."
  },
  {
    id: "prod-27",
    name: "Die-cast Vintage Racer Toy Car",
    slug: "die-cast-vintage-racer-car",
    price: 399,
    discountPrice: 299,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Metal Toys",
    image: "/assets/products/plastic-car.png",
    rating: 4.6,
    reviewCount: 24,
    stock: 18,
    featured: false,
    description: "Heavy-duty zinc alloy retro speedster model with pullback action, opening doors, and realistic engine rumble design."
  },
  {
    id: "prod-28",
    name: "Ceramic Elephant Lucky Figurine",
    slug: "ceramic-elephant-lucky-figurine",
    price: 350,
    discountPrice: 249,
    category: "Gifts",
    categoryId: "gifts",
    subcategory: "Ceramic Toys",
    image: "/assets/products/ceramic-owl.png",
    rating: 4.7,
    reviewCount: 16,
    stock: 14,
    featured: false,
    description: "Handcrafted white glazed ceramic elephant with raised trunk, decorated with gold leaf accents for home and office goodwill."
  },
  {
    id: "prod-29",
    name: "Kids Cartoon Character Soft Slippers",
    slug: "kids-cartoon-character-slippers",
    price: 249,
    discountPrice: 189,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Kids",
    image: "/assets/products/kids-slipper.png",
    rating: 4.8,
    reviewCount: 42,
    stock: 28,
    sizes: ["10", "11", "12", "13"],
    featured: true,
    description: "Colorful anti-slip EVA slides with cute embossed 3D animal face. Water-resistant and ultra-comfortable for indoor and outdoor play."
  },
  {
    id: "prod-30",
    name: "Women's Ethnic Embroidered Velvet Chappal",
    slug: "womens-ethnic-velvet-chappal",
    price: 399,
    discountPrice: 299,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Women",
    image: "/assets/products/women-slipper.png",
    rating: 4.7,
    reviewCount: 27,
    stock: 19,
    sizes: ["5", "6", "7", "8"],
    featured: false,
    description: "Traditional Kolhapuri style open-toe slip-on with intricate golden zari threadwork and padded memory insole."
  },
  {
    id: "prod-31",
    name: "Men's Daily All-Weather Waterproof Clogs",
    slug: "mens-daily-waterproof-clogs",
    price: 349,
    discountPrice: 269,
    category: "Slippers",
    categoryId: "slippers",
    subcategory: "Men",
    image: "/assets/products/men-slipper.png",
    rating: 4.5,
    reviewCount: 35,
    stock: 25,
    sizes: ["7", "8", "9", "10"],
    featured: false,
    description: "Durable washable slip-on clogs with pivoting heel strap, breathable ventilation ports, and high-traction rubber outsole."
  },
  {
    id: "prod-32",
    name: "Traditional Silk Thread Bangles Set (12 Pcs)",
    slug: "traditional-silk-thread-bangles-set",
    price: 199,
    discountPrice: 149,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Bangles",
    image: "/assets/products/bangles.png",
    rating: 4.9,
    reviewCount: 50,
    stock: 30,
    featured: true,
    description: "Hand-wound vibrant silk thread bangles studded with golden ball chain and pearl accents. Ideal for festival and bridal wear."
  },
  {
    id: "prod-33",
    name: "Sparkling Crystal Adjustable Finger Ring",
    slug: "sparkling-crystal-finger-ring",
    price: 149,
    discountPrice: 99,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Rings",
    image: "/assets/products/earrings.png",
    rating: 4.6,
    reviewCount: 18,
    stock: 40,
    featured: false,
    description: "Delicate silver-plated cocktail ring with high-facet cubic zirconia stone and adjustable comfort band."
  },
  {
    id: "prod-34",
    name: "Rose Blossom Natural Pocket Perfume 50ml",
    slug: "rose-blossom-pocket-perfume",
    price: 249,
    discountPrice: 179,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Perfumes",
    image: "/assets/products/earrings.png",
    rating: 4.7,
    reviewCount: 29,
    stock: 22,
    featured: false,
    description: "Long-lasting non-alcoholic floral fragrance spray inspired by fresh Ooty rose gardens. Travel-friendly compact bottle."
  },
  {
    id: "prod-35",
    name: "Holographic 3D Stickers Mega Pack (100 Pcs)",
    slug: "holographic-3d-stickers-mega-pack",
    price: 99,
    discountPrice: 69,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Stickers",
    image: "/assets/products/bangles.png",
    rating: 4.8,
    reviewCount: 65,
    stock: 50,
    featured: false,
    description: "Waterproof vinyl stickers featuring cute animals, motivational quotes, and kawaii doodles for laptops, bottles, and scrapbooks."
  },
  {
    id: "prod-36",
    name: "Herbal Compact Makeup Powder Kit",
    slug: "herbal-compact-makeup-powder-kit",
    price: 299,
    discountPrice: 229,
    category: "Fancy Items",
    categoryId: "fancy-items",
    subcategory: "Makeup",
    image: "/assets/products/earrings.png",
    rating: 4.5,
    reviewCount: 21,
    stock: 16,
    featured: false,
    description: "All-day oil control face powder with SPF 15 protection, infused with sandalwood and aloe vera extracts for a natural matte finish."
  },
  {
    id: "prod-37",
    name: "Cello Butterflow Blue Ballpoint Pens (Pack of 5)",
    slug: "cello-butterflow-blue-pens-pack",
    price: 99,
    discountPrice: 79,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Pens",
    image: "/assets/products/pen-set.png",
    rating: 4.9,
    reviewCount: 94,
    stock: 60,
    featured: true,
    description: "India's favorite ball pen with lubriflow ink system, ergonomic textured rubber grip, and smooth skip-free writing."
  },
  {
    id: "prod-38",
    name: "Reynolds 045 Black Fine Ballpoint Pens (Pack of 5)",
    slug: "reynolds-045-black-pens-pack",
    price: 99,
    discountPrice: 79,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Pens",
    image: "/assets/products/pen-set.png",
    rating: 4.7,
    reviewCount: 48,
    stock: 45,
    featured: false,
    description: "Classic laser tip 0.7mm fine point pens engineered for crisp examination writing and professional office documentation."
  },
  {
    id: "prod-39",
    name: "Apsara Platinum Extra Dark Pencils (Pack of 10)",
    slug: "apsara-platinum-extra-dark-pencils",
    price: 70,
    discountPrice: 59,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Pencils",
    image: "/assets/products/color-pencils.png",
    rating: 4.9,
    reviewCount: 82,
    stock: 55,
    featured: false,
    description: "Premium dark graphite lead pencils that require less pressure while writing. Includes free sharpener and eraser."
  },
  {
    id: "prod-40",
    name: "Hardbound School Record Notebook 160 Pgs",
    slug: "hardbound-school-record-notebook-160pgs",
    price: 120,
    discountPrice: 99,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Record Books",
    image: "/assets/products/spiral-notebook.png",
    rating: 4.8,
    reviewCount: 37,
    stock: 40,
    featured: false,
    description: "Heavy hardboard binding with section-sewn pages for durability. Ruling with index page, page numbers, and smooth 70 GSM paper."
  },
  {
    id: "prod-41",
    name: "Camlin Artist Oil Pastels 25 Shades",
    slug: "camlin-artist-oil-pastels-25shades",
    price: 180,
    discountPrice: 149,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Art Supplies",
    image: "/assets/products/color-pencils.png",
    rating: 4.9,
    reviewCount: 44,
    stock: 26,
    featured: false,
    description: "Vibrant, inter-mixable oil pastels with smooth blending and rich opacity. Comes with a free scraping tool for sgraffito technique."
  },
  {
    id: "prod-42",
    name: "Stainless Steel Edge Transparent Scale 30cm",
    slug: "steel-edge-transparent-scale-30cm",
    price: 49,
    discountPrice: 35,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Scales",
    image: "/assets/products/geometry-box.png",
    rating: 4.6,
    reviewCount: 29,
    stock: 50,
    featured: false,
    description: "Clear acrylic ruler with a precision stainless steel cutting edge that prevents nicking during craft cutter usage."
  },
  {
    id: "prod-43",
    name: "Non-Dust Jumbo Eraser & Sharpener Combo",
    slug: "non-dust-jumbo-eraser-sharpener-combo",
    price: 45,
    discountPrice: 35,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Erasers",
    image: "/assets/products/geometry-box.png",
    rating: 4.8,
    reviewCount: 60,
    stock: 75,
    featured: false,
    description: "Dust-free eraser that rolls up residue into strands without tearing paper, paired with an anti-rust angled blade pencil sharpener."
  },
  {
    id: "prod-44",
    name: "Expanding Accordion Document File 12 Pockets",
    slug: "expanding-accordion-document-file-12pockets",
    price: 249,
    discountPrice: 199,
    category: "Stationery",
    categoryId: "stationery",
    subcategory: "Files",
    image: "/assets/products/spiral-notebook.png",
    rating: 4.7,
    reviewCount: 33,
    stock: 22,
    featured: false,
    description: "Heavy-duty polypropylene accordion file with 12 colored tabbed compartments and secure elastic cord lock. Fits A4 & legal certificates."
  }
];

export const CATEGORIES = [
  { id: "all", name: "All Products", icon: "Grid", slug: "all" },
  { id: "gifts", name: "Gifts", icon: "Gift", slug: "gifts", subcategories: ["Soft Toys", "Teddy Bears", "Metal Toys", "Ceramic Toys", "Plastic Toys", "Wooden Toys"] },
  { id: "slippers", name: "Slippers", icon: "Footprints", slug: "slippers", subcategories: ["Men", "Women", "Kids"] },
  { id: "fancy-items", name: "Fancy Items", icon: "Gem", slug: "fancy-items", subcategories: ["Earrings", "Chains", "Rings", "Bangles", "Stickers", "Makeup", "Perfumes"] },
  { id: "stationery", name: "Stationery", icon: "PenTool", slug: "stationery", subcategories: ["Pens", "Pencils", "Notebooks", "Record Books", "Drawing Books", "Erasers", "Sharpeners", "Geometry Boxes", "Scales", "Color Pencils", "Sketch Pens", "Markers", "Files", "Folders", "Art Supplies", "School Supplies", "Office Supplies"] }
];
